  <footer class="site-footer cf" role="contentinfo">
  
  <svg class="svg-angle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" preserveAspectRatio="none">
  	<polygon points="0,50 50,50 0,0" fill="inherit" />
  </svg>

    <a class="icon--social twitter" target="_BLANK" href="https://twitter.com/j4n_co">
      twitter
    </a>
    <a class="icon--social linkedin" target="_BLANK" href="http://ca.linkedin.com/in/jandrewniak">
        linkedin
    </a>
    <a class="icon--social codepen" target="_BLANK" href="http://codepen.io/j4n">
        codepen
    </a>

  <script type="text/javascript" language="javascript">
  <!-- // Generated by http://rumkin.com/tools/mailto_encoder
  ML="wadb:rl<"+"\"c=eo@sm-pfuh jgk>in.t/";
  MI="71E961>>:83CMM<"+"K@@6<"+"KGE9<"+"KM;KM@051AA;5@@K155<"+"08ED5;B:8?1J6M<"+"4F1KL25;0KJ1H=G?1J6L9<"+"?8IEG;MEJKEM<"+"C9DE7N1IE";
  OT="";
  for(j=0;j<MI.length;j++){
  OT+=ML.charAt(MI.charCodeAt(j)-48);
  }document.write(OT);
  // --></script>
  
  <nav class="footer-nav">
    <a href="/">home</a>
    <a href="/portfolio">work</a>
    <a href="/lab">lab</a>
    <a href="/blog">blog</a>
  </nav>

	<small class="text-center">
		© Jan Drewniak 2015  &middot;  Built with <a href="http://getkirby.com">Kirby CMS</a>  &middot;  Hosted on <a href="https://www.webfaction.com/?aid=21613">Webfaction</a>  &middot;  Set in Avenir & Glypha
	</small>


  </footer>

  <?php echo js('assets/js/all.min.js') ?>
  
  <?php if ( isset($page_scripts) ): ?>

  <?php foreach( $page_scripts as $script): ?>
    <?php if ( preg_match('/paperscript/', $script) ){
      echo "<script src=".$script." type='text/paperscript' canvas='canvas'></script>"; 
    } else {
      echo js($script); 
    }
    ?>
  <?php endforeach ?> 
	
  <?php endif ?>

  <?php echo $page->custom_js(); ?>


</body>

</html>