<?php snippet('header') ?>
<?php $work = $pages->find('portfolio')->children()->visible(); ?> 

<header id="home" class="container--header">
	
	<div class="container--fixed">

		<canvas id="canvas" resize="true"></canvas>
		
		<div class="row">
			<article class="right-textbox">
				<h1 class="headline glitch"><?php echo $page->headline() ?></h1>
				<h2 class="subhead"><?php echo $page->subhead() ?></h2>
				<?php echo kirbytext($page->text()) ?>
				<script type="text/javascript" language="javascript">
				<!-- // Generated by http://rumkin.com/tools/mailto_encoder
				ML="\"mbhu=gwdflok-.jr@>n:p cta/'isex<";
				MI="PIFG:IMM5024HH;C0F3@N9501IL:H;D?IC>8@N7CLI<"+"A61IL:>G;10BPMEICFG:IMM5024HH;C=HNOH0BF:NHKMFHI:<"+"PJMEICBPJIB";
				OT="";
				for(j=0;j<MI.length;j++){
				OT+=ML.charAt(MI.charCodeAt(j)-48);
				}document.write(OT);
				// --></script>

			</article>
		</div> 
	</div>	

</header>

<main class="main" role="main">

	<section id="portfolio" class="container--below-fixed work-section">

		<svg class="svg-angle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" preserveAspectRatio="none">
			<polygon points="50,0 0,50 50,50" fill="inherit" />
		</svg>


		<h2 class="headline--vertical">work</h2>
		
		<div class="row">
				
				<div class="owl-carousel">

					<?php foreach( $work as $item): ?>
						<div class="flat3D">
							<img src="<?php echo $item->images()->find('home_original.jpg')->url() ?>"/>
							<a href="#<?php echo str_replace("+","_", urlencode($item->title()));?>" class="button--dark js-carousel-link">
								read more about <?php echo $item->title(); ?> 
							</a>
						</div>
					<?php endforeach ?> 

				</div>
					
				<div class="js-carousel-description-container">
				<?php foreach( $work as $item): ?>
					<article class="js-carousel-description" id="<?php echo str_replace("+","_", urlencode($item->title()));?>">
						<h3 class="headline--medium"><?php echo $item->title(); ?></h3>
						<?php echo kirbytext($item->text()); ?> 
					

						<? // GALLERY IMAGES ?>
						<? foreach($item->images() AS $image): ?>
							<? if( intval($image->name()) > 0 ): ?> 
								<img class="gallery-image" src="<?php echo $image->url(); ?>" />
							<? endif ?> 
						<? endforeach ?>

					</article>
				<?php endforeach ?> 
				</div>	
		</div>


	</section>


	<section id="lab"  class="container--below-fixed lab-section">

		<svg class="svg-angle" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" preserveAspectRatio="none">
			<polygon points="0,50 50,50 0,0" fill="inherit" />
		</svg>

		<h2 class="headline--vertical">Lab</h2>
		
		<div class="row">
			<?php $lab = $pages->find('lab')->children()->visible(); ?> 
			<?php foreach( $lab as $item): ?>
				<?php $icon =  $item->files()->find('icon.jpg', 'icon.png')->first()->url(); ?>
				<?php $preview =  $item->files()->find('preview.gif'); ?>
				
				<?php $preview = ( is_null($preview) ? 'false' : $item->files()->find('preview.gif')->url() );?>  
				<a href="<?php echo $item->url(); ?>" class="col--asym lab lab-grid-item">
					<span class="lab-grid-item__front" style="background-image:url(<?php echo $icon ?>);"></span>
					<span class="lab-grid-item__back" style="background-image:url(<?php echo $preview ?>);"></span>
				</a>
			<?php endforeach ?> 
		</div>

	</section>


	<section id="blog" class="container--below-fixed blog-section skin--white">

		<svg class="svg-angle" xmlns="http://www.w3.org/2000/svg" width="100%" height="50px" viewBox="0 0 50 50" preserveAspectRatio="none">
			<polygon points="50,0 0,50 50,50" fill="inherit" />
		</svg>
		
		<h2 class="headline--vertical">Blog</h2>

		<div class="row">

			<?php $blog = $pages->find('blog')->children()->visible()->limit(7); ?> 
			<?php foreach( $blog as $item): ?>
				
				<article class="post-summary">
					<time itemprop="datePublished" pubdate datetime="<?= $item->date('m/d/Y')?>" title="<?= $item->date('M d, Y')?>"><span class="date"> <?= $item->date('m/d')?></span><span class="year"><?= $item->date('Y')?></span></time>
					<a class="blog-link" href="<?php echo $item->url();?>"><?php echo $item->title(); ?></a>
				</article>

			<?php endforeach ?> 
			<a href="/blog" class='button'>
				Visit Blog
			</a>
		
		</div>
	
	</section>

</main>

<?php snippet('footer', array('page_scripts' => 
							array($page->file('paper-core.js')->url(), 
								  $page->file('paperscript.js')->url(),  
								  $page->file('scrollr.min.js')->url() 
								  ) 
							)
			  ) ?>

